# Generated by Django 5.0.8 on 2026-05-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='datasource',
            new_name='ingestion_d_tenant__8e99b2_idx',
            old_name='ingestion_d_tenant__d9aeda_idx',
        ),
        migrations.RenameIndex(
            model_name='rawupload',
            new_name='ingestion_r_tenant__1e5df0_idx',
            old_name='ingestion_r_tenant__ff3cab_idx',
        ),
    ]
