# Generated by Django 5.0.8 on 2026-05-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emissionrecord',
            new_name='emissions_e_tenant__860cd1_idx',
            old_name='emissions_e_tenant__cd4dc0_idx',
        ),
        migrations.RenameIndex(
            model_name='emissionrecord',
            new_name='emissions_e_tenant__2cce63_idx',
            old_name='emissions_e_tenant__713624_idx',
        ),
        migrations.RenameIndex(
            model_name='emissionrecord',
            new_name='emissions_e_source__edbb62_idx',
            old_name='emissions_e_source__d72f86_idx',
        ),
    ]
