# Generated by Django 5.0.8 on 2026-05-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_tenant__f6fa3d_idx',
            old_name='audit_audit_tenant__38d477_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_timesta_19e18a_idx',
            old_name='audit_audit_timesta_023417_idx',
        ),
    ]
